# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rbcurse}
  s.version = "1.2.0.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rahul Kumar"]
  s.date = %q{2010-12-20}
  s.description = %q{Ruby curses widgets for easy application development on text terminals (ruby 1.9, 1.8)}
  s.email = %q{sentinel.2001@gmx.com}
  s.extra_rdoc_files = [
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "History.txt",
    "Makefile",
    "Manifest.txt",
    "NOTES",
    "README.markdown",
    "TODO",
    "TODO2.txt",
    "VERSION",
    "examples/README.txt",
    "examples/abasiclist.rb",
    "examples/alpmenu.rb",
    "examples/appdirtree.rb",
    "examples/appemail.rb",
    "examples/appemaillb.rb",
    "examples/appgcompose.rb",
    "examples/appgmail.rb",
    "examples/atree.rb",
    "examples/data.txt",
    "examples/dirtree.rb",
    "examples/keytest.rb",
    "examples/menu1.rb",
    "examples/mpad2.rb",
    "examples/multispl.rb",
    "examples/newtesttabp.rb",
    "examples/qdfilechooser.rb",
    "examples/rfe.rb",
    "examples/rfe_renderer.rb",
    "examples/rmail.rb",
    "examples/splitp.rb",
    "examples/sqlc.rb",
    "examples/sqlm.rb",
    "examples/status.txt",
    "examples/table1.rb",
    "examples/term2.rb",
    "examples/test1.rb",
    "examples/test2.rb",
    "examples/testchars.rb",
    "examples/testcombo.rb",
    "examples/testkeypress.rb",
    "examples/testlistbox.rb",
    "examples/testmenu.rb",
    "examples/testmulticomp.rb",
    "examples/testmultispl.rb",
    "examples/testree.rb",
    "examples/testscroller.rb",
    "examples/testscrolllb.rb",
    "examples/testscrollp.rb",
    "examples/testscrollta.rb",
    "examples/testscrolltable.rb",
    "examples/testsplit.rb",
    "examples/testsplit2.rb",
    "examples/testsplit3.rb",
    "examples/testsplit3_1.rb",
    "examples/testsplit3a.rb",
    "examples/testsplit3b.rb",
    "examples/testsplitta.rb",
    "examples/testsplittv.rb",
    "examples/testsplittvv.rb",
    "examples/testtable.rb",
    "examples/testtabp.rb",
    "examples/testtodo.rb",
    "examples/testtpane.rb",
    "examples/testtpane2.rb",
    "examples/testtpanetable.rb",
    "examples/testvimsplit.rb",
    "examples/todo.db",
    "examples/todo.yml",
    "examples/todocsv.csv",
    "examples/viewtodo.rb",
    "lib/rbcurse.rb",
    "lib/rbcurse/action.rb",
    "lib/rbcurse/app.rb",
    "lib/rbcurse/applicationheader.rb",
    "lib/rbcurse/celleditor.rb",
    "lib/rbcurse/checkboxcellrenderer.rb",
    "lib/rbcurse/colormap.rb",
    "lib/rbcurse/comboboxcellrenderer.rb",
    "lib/rbcurse/defaultlistselectionmodel.rb",
    "lib/rbcurse/extras/bottomline.rb",
    "lib/rbcurse/extras/directorylist.rb",
    "lib/rbcurse/extras/directorytree.rb",
    "lib/rbcurse/extras/divider.rb",
    "lib/rbcurse/extras/focusmanager.rb",
    "lib/rbcurse/extras/listselectable.rb",
    "lib/rbcurse/extras/masterdetail.rb",
    "lib/rbcurse/extras/menutree.rb",
    "lib/rbcurse/extras/rlink.rb",
    "lib/rbcurse/extras/rmenulink.rb",
    "lib/rbcurse/extras/scrollbar.rb",
    "lib/rbcurse/extras/stdscrwindow.rb",
    "lib/rbcurse/extras/tableextended.rb",
    "lib/rbcurse/extras/tabular.rb",
    "lib/rbcurse/extras/tabularwidget.rb",
    "lib/rbcurse/extras/viewer.rb",
    "lib/rbcurse/io.rb",
    "lib/rbcurse/keylabelprinter.rb",
    "lib/rbcurse/listcellrenderer.rb",
    "lib/rbcurse/listeditable.rb",
    "lib/rbcurse/listkeys.rb",
    "lib/rbcurse/listscrollable.rb",
    "lib/rbcurse/listselectable.rb",
    "lib/rbcurse/mapper.rb",
    "lib/rbcurse/orderedhash.rb",
    "lib/rbcurse/ractionevent.rb",
    "lib/rbcurse/rbasiclistbox.rb",
    "lib/rbcurse/rchangeevent.rb",
    "lib/rbcurse/rcombo.rb",
    "lib/rbcurse/rcommandwindow.rb",
    "lib/rbcurse/rdialogs.rb",
    "lib/rbcurse/rinputdataevent.rb",
    "lib/rbcurse/rlistbox.rb",
    "lib/rbcurse/rmenu.rb",
    "lib/rbcurse/rmessagebox.rb",
    "lib/rbcurse/rmulticontainer.rb",
    "lib/rbcurse/rmultisplit.rb",
    "lib/rbcurse/rmultitextview.rb",
    "lib/rbcurse/rpopupmenu.rb",
    "lib/rbcurse/rprogress.rb",
    "lib/rbcurse/rscrollform.rb",
    "lib/rbcurse/rscrollpane.rb",
    "lib/rbcurse/rsplitpane.rb",
    "lib/rbcurse/rsplitpane2.rb",
    "lib/rbcurse/rtabbedpane.rb",
    "lib/rbcurse/rtabbedwindow.rb",
    "lib/rbcurse/rtable.rb",
    "lib/rbcurse/rtextarea.rb",
    "lib/rbcurse/rtextview.rb",
    "lib/rbcurse/rtree.rb",
    "lib/rbcurse/rviewport.rb",
    "lib/rbcurse/rvimsplit.rb",
    "lib/rbcurse/rwidget.rb",
    "lib/rbcurse/scrollable.rb",
    "lib/rbcurse/table/tablecellrenderer.rb",
    "lib/rbcurse/table/tabledatecellrenderer.rb",
    "lib/rbcurse/tree/treecellrenderer.rb",
    "lib/rbcurse/tree/treemodel.rb",
    "lib/rbcurse/undomanager.rb",
    "lib/rbcurse/vieditable.rb",
    "lib/ver/keyboard.rb",
    "lib/ver/keyboard2.rb",
    "lib/ver/ncurses.rb",
    "lib/ver/window.rb",
    "test/test_rbcurse.rb"
  ]
  s.homepage = %q{http://github.com/farmisen/rbcurse}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby curses widgets for easy application development on text terminals (ruby 1.9, 1.8)}
  s.test_files = [
    "examples/abasiclist.rb",
    "examples/alpmenu.rb",
    "examples/appdirtree.rb",
    "examples/appemail.rb",
    "examples/appemaillb.rb",
    "examples/appgcompose.rb",
    "examples/appgmail.rb",
    "examples/atree.rb",
    "examples/dirtree.rb",
    "examples/keytest.rb",
    "examples/menu1.rb",
    "examples/mpad2.rb",
    "examples/multispl.rb",
    "examples/newtesttabp.rb",
    "examples/qdfilechooser.rb",
    "examples/rfe.rb",
    "examples/rfe_renderer.rb",
    "examples/rmail.rb",
    "examples/splitp.rb",
    "examples/sqlc.rb",
    "examples/sqlm.rb",
    "examples/table1.rb",
    "examples/term2.rb",
    "examples/test1.rb",
    "examples/test2.rb",
    "examples/testchars.rb",
    "examples/testcombo.rb",
    "examples/testkeypress.rb",
    "examples/testlistbox.rb",
    "examples/testmenu.rb",
    "examples/testmulticomp.rb",
    "examples/testmultispl.rb",
    "examples/testree.rb",
    "examples/testscroller.rb",
    "examples/testscrolllb.rb",
    "examples/testscrollp.rb",
    "examples/testscrollta.rb",
    "examples/testscrolltable.rb",
    "examples/testsplit.rb",
    "examples/testsplit2.rb",
    "examples/testsplit3.rb",
    "examples/testsplit3_1.rb",
    "examples/testsplit3a.rb",
    "examples/testsplit3b.rb",
    "examples/testsplitta.rb",
    "examples/testsplittv.rb",
    "examples/testsplittvv.rb",
    "examples/testtable.rb",
    "examples/testtabp.rb",
    "examples/testtodo.rb",
    "examples/testtpane.rb",
    "examples/testtpane2.rb",
    "examples/testtpanetable.rb",
    "examples/testvimsplit.rb",
    "examples/viewtodo.rb",
    "test/test_rbcurse.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

